---
title: "Registros de VIH correlacionado con diversos factores"
author: "Amina Khantimirova, Wiam Messari y Emma Arrieta"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    theme: flatly     
    highlight: tango  
    df_print: paged 
---

<style>
body {
  text-align: justify;
  font-family: "Poppins", "Segoe UI", sans-serif;
  background-color: #fff0f5;
  color: #333;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## **Introducción**

El **VIH** significa virus de inmunodeficiencia humana. Daña su sistema inmunitario al destruir un tipo de glóbulo blanco que ayuda a su cuerpo a combatir las infecciones. Esto lo pone en riesgo de tener otras infecciones y enfermedades.

Esta enfermedad afecta a un gran porcentaje de la población española, resultando en un foco de malestar. En este seminario estudiaremos aquellos indicativos que potencian la expresión de dicha enfermedad. 

Nuestro primer foco de interés es estudiar la correlación entre la orientación sexual y el VIH, pero también incluiresmos otros factores de riesgo que podrían desencadenar el virus.




